services:
  mongodb:
    image: mongo:4.4.4
    ports:
      - 27017:27017

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.11.2
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
